import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} font-light text-[var(--text-color)] bg-[var(--black-color)] tracking-wide transition-all duration-200 ease-in-out`}
      >
        {children}
      </body>
    </html>
  );
}
